name: Local
values:
  - key: baseurl
    enabled: true
    value: ''
  - key: bearertoken
    enabled: true
    value: ''
  - key: Admintoken
    enabled: true
    value: ''
  - key: accountId
    enabled: true
    value: ''
